### ISSUE TITLE
**Meta**

### ISSUE THREAD

**Issue by samakunchan** [samakunchan/samatech#73]
- [ ] Faire la meta description
- [ ] Faire les meta keyword par page
- [ ] Mettre les metas facebook, google, twitter
